### ISSUE TITLE
Style Guidlines

### ISSUE THREAD

**Issue by DanielRX** [JoshuaPaulBarnard/PokeIdle#1]
Using jshint throws up 100+ errors, the source of main.js needs to be edited to fix this

I have most of this done if you would like a PR.

**Comment by JoshuaPaulBarnard** [comment]
yes i know, the guy who wrote the basics for this game coded it in a very odd way.

sure, i would love to see what you've done!

**Comment by DanielRX** [comment]
I would have before the miner issue. I refuse to support that practice.

**Comment by JoshuaPaulBarnard** [comment]
ah yeah, sorry about that.  I just made this post to reddit:
Hey guys, sorry about the webminer on the website. I'm studying web development right now and found out about them and was playing around with them last night to see how they work, what they do. I'm thinking of using them to monetize some of my other sits, but this is the project i'm working on now. Anyways, I uploaded the wrong files last night. I know it sounds totally lame :-P

so yeah, sorry about that, its been removed.

ps. if i ever do add monitization such as with a miner, i'd rather go with one like coinhive that lets people opt-in/out.
______________________________________________________________

So yeah, i hope you can forgive me.  it was an honest mistake.  i uploaded everything last night before going to bed, thats why i havn't been able to respond until now
